spring:
  application:
    name: s3-kotlin


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    services:
      s3:
        url: ${S3_URL}
        bucket: ${BUCKET_NAME}
logging:
  level:
    org.springframework.web.client: DEBUG
