spring:
  application:
    name: s3-kotlin


  config:
    activate:
      on-profile: localstack

cloud:
  aws:
    endpoint: http://localhost:4566  # URL do LocalStack (se estiver usando LocalStack)
    credentials:
      access-key: test
      secret-key: test
      bucket-name: s3-test
logging:
  level:
    org.springframework.web.client: DEBUG
